//	stationaryorbit.graphics-core:/interpolation
//	Copyright 2020 zawa-ch.
//	GPLv3 (or later) license
//
//	This program is free software: you can redistribute it and/or modify
//	it under the terms of the GNU General Public License as published by
//	the Free Software Foundation, either version 3 of the License, or
//	any later version.
//
//	This program is distributed in the hope that it will be useful,
//	but WITHOUT ANY WARRANTY; without even the implied warranty of
//	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//	See the GNU General Public License for more details.
//
//	You should have received a copy of the GNU General Public License
//	along with this program.
//	If not, see <http://www.gnu.org/licenses/>.
//
#include "stationaryorbit/graphics-core/interpolation.hpp"

template zawa_ch::StationaryOrbit::Graphics::GrayScale1_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScale1_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScale8_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScale8_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScale16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScale16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScale32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScale32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScale64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScale64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScaleI16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScaleI16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScaleI32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScaleI32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScaleI64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScaleI64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScaleF32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScaleF32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScaleF64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScaleF64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMY8_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMY8_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMY16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMY16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMY32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMY32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMY64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMY64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYI16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMYI16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYI32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMYI32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYI64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMYI64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYF32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMYF32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYF64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMYF64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMY8_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMY8_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMY16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMY16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMY32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMY32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMY64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMY64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYI16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYI16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYI32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYI32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYI64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYI64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYF32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYF32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYF64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYF64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYK8_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMYK8_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYK16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMYK16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYK32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMYK32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYK64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMYK64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYKI16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMYKI16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYKI32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMYKI32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYKI64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMYKI64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYKF32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMYKF32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYKF64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<CMYKF64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYK8_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYK8_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYK16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYK16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYK32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYK32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYK64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYK64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYKI16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYKI16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYKI32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYKI32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYKI64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYKI64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYKF32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYKF32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYKF64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYKF64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGB8_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<RGB8_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGB16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<RGB16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGB32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<RGB32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGB64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<RGB64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGBI16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<RGBI16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGBI32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<RGBI32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGBI64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<RGBI64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGBF32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<RGBF32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGBF64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<RGBF64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGB8_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ARGB8_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGB16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ARGB16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGB32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ARGB32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGB64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ARGB64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGBI16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ARGBI16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGBI32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ARGBI32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGBI64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ARGBI64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGBF32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ARGBF32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGBF64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::NearestNeighbor(const zawa_ch::StationaryOrbit::Graphics::Image<ARGBF64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScale1_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScale1_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScale8_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScale8_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScale16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScale16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScale32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScale32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScale64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScale64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScaleI16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScaleI16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScaleI32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScaleI32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScaleI64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScaleI64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScaleF32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScaleF32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::GrayScaleF64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<GrayScaleF64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMY8_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMY8_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMY16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMY16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMY32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMY32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMY64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMY64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYI16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMYI16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYI32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMYI32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYI64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMYI64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYF32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMYF32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYF64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMYF64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMY8_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMY8_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMY16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMY16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMY32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMY32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMY64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMY64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYI16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYI16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYI32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYI32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYI64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYI64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYF32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYF32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYF64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYF64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYK8_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMYK8_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYK16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMYK16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYK32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMYK32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYK64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMYK64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYKI16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMYKI16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYKI32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMYKI32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYKI64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMYKI64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYKF32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMYKF32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::CMYKF64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<CMYKF64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYK8_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYK8_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYK16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYK16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYK32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYK32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYK64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYK64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYKI16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYKI16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYKI32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYKI32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYKI64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYKI64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYKF32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYKF32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ACMYKF64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ACMYKF64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGB8_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<RGB8_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGB16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<RGB16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGB32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<RGB32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGB64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<RGB64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGBI16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<RGBI16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGBI32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<RGBI32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGBI64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<RGBI64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGBF32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<RGBF32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::RGBF64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<RGBF64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGB8_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ARGB8_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGB16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ARGB16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGB32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ARGB32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGB64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ARGB64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGBI16_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ARGBI16_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGBI32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ARGBI32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGBI64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ARGBI64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGBF32_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ARGBF32_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
template zawa_ch::StationaryOrbit::Graphics::ARGBF64_t zawa_ch::StationaryOrbit::Graphics::ImageInterpolation::Bilinear(const zawa_ch::StationaryOrbit::Graphics::Image<ARGBF64_t>&, const zawa_ch::StationaryOrbit::Graphics::DisplayPointF&);
